cleos push action -s -j -d eosio setalimits '{"account": "eosio.bpay", "ram_bytes": 5184, "net_weight": -1, "cpu_weight": -1}' -p eosio
cleos push action -s -j -d eosio setalimits '{"account": "eosio.vpay", "ram_bytes": 8720, "net_weight": -1, "cpu_weight": -1}' -p eosio
cleos push action -s -j -d eosio setalimits '{"account": "eosio.msig", "ram_bytes": 221325, "net_weight": -1, "cpu_weight": -1}' -p eosio
cleos push action -s -j -d eosio setalimits '{"account": "eosio.token", "ram_bytes": 217920, "net_weight": -1, "cpu_weight": -1}' -p eosio
cleos push action -s -j -d eosio setalimits '{"account": "eosio.names", "ram_bytes": 46106292, "net_weight": -1, "cpu_weight": -1}' -p eosio
cleos push action -s -j -d eosio setalimits '{"account": "eosio.ram", "ram_bytes": 305824, "net_weight": -1, "cpu_weight": -1}' -p eosio
cleos push action -s -j -d eosio setalimits '{"account": "eosio.ramfee", "ram_bytes": 2688, "net_weight": -1, "cpu_weight": -1}' -p eosio
cleos push action -s -j -d eosio setalimits '{"account": "eosio.saving", "ram_bytes": 2688, "net_weight": -1, "cpu_weight": -1}' -p eosio
cleos push action -s -j -d eosio setalimits '{"account": "eosio.stake", "ram_bytes": 403952, "net_weight": -1, "cpu_weight": -1}' -p eosio
